# Generated by Django 4.1 on 2022-11-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_jan', models.JSONField(null=True)),
                ('month_feb', models.JSONField(null=True)),
                ('month_mar', models.JSONField(null=True)),
                ('month_apr', models.JSONField(null=True)),
                ('month_may', models.JSONField(null=True)),
                ('month_jun', models.JSONField(null=True)),
                ('month_jul', models.JSONField(null=True)),
                ('month_aug', models.JSONField(null=True)),
                ('month_sep', models.JSONField(null=True)),
                ('month_oct', models.JSONField(null=True)),
                ('month_nov', models.JSONField(null=True)),
                ('month_dec', models.JSONField(null=True)),
                ('uid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
