# Generated by Django 4.1 on 2022-11-19 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalExpenses', '0002_rename_month_apr_userexpense_april_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpense',
            name='id',
        ),
        migrations.AddField(
            model_name='userexpense',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='uid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
