# Generated by Django 4.1 on 2022-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0004_remove_userexpense_user_userexpense_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpense',
            name='uid',
            field=models.TextField(max_length=10),
        ),
    ]
