# Generated by Django 4.1 on 2022-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0005_alter_userexpense_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.TextField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='April',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='August',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='December',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='February',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='January',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='July',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='June',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='March',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='May',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='November',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='October',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='September',
        ),
        migrations.AddField(
            model_name='userexpense',
            name='expense',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='income',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='month',
            field=models.TextField(default='January', max_length=12),
        ),
        migrations.AddField(
            model_name='userexpense',
            name='saving',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
