# Generated by Django 4.1 on 2022-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0006_user_remove_userexpense_april_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.TextField(max_length=20),
        ),
    ]
