# Generated by Django 4.1 on 2022-11-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.TextField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
