# Generated by Django 4.1 on 2022-11-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personalExpenses', '0011_remove_user_id_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexpense',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='uid',
            field=models.TextField(auto_created=True, default=1, max_length=10),
            preserve_default=False,
        ),
    ]
