# Generated by Django 4.1 on 2022-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0012_userexpense_user_alter_userexpense_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexpense',
            name='expense',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='month',
            field=models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'Aug'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='userexpense',
            name='saving',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
