# Generated by Django 4.1 on 2022-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalExpenses', '0014_remove_user_uid_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexpense',
            name='uid',
        ),
    ]
